const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],SHIFTS=[['day','Day Shift','07:00–19:00'],['night','Night Shift','19:00–07:00']],KEY='friendlyShiftPlanner';const $=id=>document.getElementById(id);
function local(v){let[a,b,c]=v.split('-').map(Number);return new Date(a,b-1,c)}
function monday(d){d=new Date(d);let n=d.getDay();d.setDate(d.getDate()-(n===0?6:n-1));d.setHours(0,0,0,0);return d}
function key(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function fmt(d){return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(d)}
function money(n){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n)}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return{}}}
function save(){let s={start:$('start').value,rate:$('rate').value,tax:$('tax').value,ni:$('ni').value,checked:{}};document.querySelectorAll('.shift input').forEach(x=>{if(x.checked)s.checked[x.dataset.id]=1});localStorage.setItem(KEY,JSON.stringify(s))}
function render(){let st=monday(local($('start').value));$('start').value=key(st);let old=load();$('weeks').innerHTML='';$('tabs').innerHTML='';
for(let w=0;w<4;w++){let a=new Date(st);a.setDate(a.getDate()+w*7);let z=new Date(a);z.setDate(z.getDate()+6);
let tab=document.createElement('button');tab.className='week-tab'+(w===0?' active':'');tab.dataset.week=w;tab.innerHTML='Week '+(w+1)+'<small>'+fmt(a)+' – '+fmt(z)+'</small>';tab.onclick=()=>showWeek(w);$('tabs').append(tab);
let sec=document.createElement('section');sec.className='card week'+(w===0?' active':'');sec.dataset.week=w;sec.innerHTML='<div class="week-head"><strong>Week '+(w+1)+'</strong><span>'+fmt(a)+' – '+fmt(z)+'</span></div><div class="days"></div>';$('weeks').append(sec);let box=sec.querySelector('.days');
for(let i=0;i<7;i++){let d=new Date(a);d.setDate(a.getDate()+i),id=key(d);let row=document.createElement('div');row.className='day';row.innerHTML='<div class="dayinfo"><strong>'+DAYS[i]+'</strong><div class="date">'+fmt(d)+'</div></div>'+SHIFTS.map(s=>'<label class="shift"><input type="checkbox" data-id="'+id+'-'+s[0]+'" data-week="'+w+'" data-hours="12"><span class="check"></span><span class="shifttext"><strong>'+s[1]+'</strong><time>'+s[2]+' · 12 hrs</time></span></label>').join('');box.append(row)}} 
document.querySelectorAll('.shift input').forEach(x=>{x.checked=!!old.checked?.[x.dataset.id];x.onchange=()=>{save();calc()}});calc()}
function showWeek(w){document.querySelectorAll('.week').forEach(x=>x.classList.toggle('active',+x.dataset.week===w));document.querySelectorAll('.week-tab').forEach(x=>x.classList.toggle('active',+x.dataset.week===w));window.scrollTo({top:document.querySelector('.week.active').offsetTop-12,behavior:'smooth'})}
function tax(a){let t=Math.max(0,a-12570),x=Math.min(t,37700)*.2;t-=37700;if(t>0){x+=Math.min(t,87570)*.4;t-=87570}if(t>0)x+=t*.45;return x}
function ni(a,c){if(c==='C'||a<=12570)return 0;let r=c==='B'?.0185:.02;return Math.max(0,Math.min(a,50270)-12570)*r+Math.max(0,a-50270)*.02}
function calc(){let rate=+$('rate').value||0,w=Array(4).fill(0),h=Array(4).fill(0),n=0;document.querySelectorAll('.shift input:checked').forEach(x=>{n++;w[+x.dataset.week]++;h[+x.dataset.week]+=12});let H=h.reduce((a,b)=>a+b,0),G=H*rate,A=G*13,T=tax(A)/13,N=ni(A,$('ni').value)/13,net=Math.max(0,G-T-N);$('shifts').textContent=n;$('hours').textContent=H;$('gross').textContent=money(G);$('it').textContent=money(T);$('niout').textContent=money(N);$('net').textContent=money(net);$('deduct').textContent=G?((T+N)/G*100).toFixed(2)+'%':'0.00%';$('avg').textContent=money(net/4);
$('breakdown').innerHTML='<div class="row head"><div>Week</div><div>Shifts</div><div>Hours</div><div>Gross</div><div>Est. net</div></div>'+h.map((x,i)=>{let g=x*rate,t=tax(g*13)/13,n2=ni(g*13,$('ni').value)/13;return '<div class="row"><strong>Week '+(i+1)+'</strong><div>'+w[i]+'</div><div>'+x+'</div><div>'+money(g)+'</div><div>'+money(Math.max(0,g-t-n2))+'</div></div>'}).join('');save()}
function init(){let s=load(),d=monday(new Date());$('start').value=s.start||key(d);$('rate').value=s.rate??14;$('tax').value=s.tax||'1257L';$('ni').value=s.ni||'A';render();$('start').onchange=render;['rate','tax','ni'].forEach(id=>$(id).oninput=calc);$('reset').onclick=()=>{localStorage.removeItem(KEY);location.reload()}}init();